version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./webapp:/opt/webapp
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      ##### Mac OS X and Linux ONLY #####
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
